package simulator;

/*
 * @author Ashlesha Lapalkar
 * @version 1.1
 * 
 */

import java.awt.Color;
import java.net.URL;
import java.util.Calendar;
import java.util.HashMap;
import java.util.List;

import javax.media.ControllerEvent;
import javax.media.ControllerListener;
import javax.media.EndOfMediaEvent;
import javax.media.Manager;
import javax.media.MediaLocator;
import javax.media.Player;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JDialog;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.SwingUtilities;
import javax.swing.Timer;

import sensorFactory.MotionSensor;
import sensorFactory.Sensor;
import sensorFactory.TempSensor;
import singletonLogger.*;
import systems.*;


/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author saurabh
 */
public class SimulatorGUI extends javax.swing.JFrame {

	List<Sensor> sensorList;
	MainSystem sys;
	HashMap<Integer, JPanel> panelMap = new HashMap<>();
	HashMap<Integer, JLabel> labelMap = new HashMap<>();
	String responseCode = null;
	AlarmRinger ringer;
    /**
     * Creates new form home
     */
    public SimulatorGUI() {
        initComponents();
    }
    
    public SimulatorGUI(List<Sensor> sensorList, MainSystem sys){
    	this.sensorList = sensorList;
    	this.sys = sys;
    	ringer = new AlarmRinger();
    	initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        topPanel = new javax.swing.JPanel();
        bldgPanel = new javax.swing.JPanel();
        secAPanel = new javax.swing.JPanel();
        panelRoom1 = new javax.swing.JPanel();
        sec1Room1Breakin = new javax.swing.JButton();
        sec1Room1Fire = new javax.swing.JButton();
        Room1Label = new javax.swing.JLabel();
        panelRoom2 = new javax.swing.JPanel();
        Room2 = new javax.swing.JLabel();
        sec1Room2Breakin = new javax.swing.JButton();
        sec1Room2Fire = new javax.swing.JButton();
        Room2Label = new javax.swing.JLabel();
        panelRoom3 = new javax.swing.JPanel();
        Room3 = new javax.swing.JLabel();
        sec1Room3Fire = new javax.swing.JButton();
        sec1Room3Breakin = new javax.swing.JButton();
        Room3Label = new javax.swing.JLabel();
        panelRoom4 = new javax.swing.JPanel();
        Room4 = new javax.swing.JLabel();
        sec1Room4Breakin = new javax.swing.JButton();
        sec1Room4Fire = new javax.swing.JButton();
        Room4Label = new javax.swing.JLabel();
        secBPanel = new javax.swing.JPanel();
        panelRoom5 = new javax.swing.JPanel();
        Room1B = new javax.swing.JLabel();
        sec2Room5Breakin = new javax.swing.JButton();
        sec2Room5Fire = new javax.swing.JButton();
        Room5Label = new javax.swing.JLabel();
        panelRoom6 = new javax.swing.JPanel();
        sec2Room6Breakin = new javax.swing.JButton();
        sec2Room6Fire = new javax.swing.JButton();
        Room6Label = new javax.swing.JLabel();
        panelRoom7 = new javax.swing.JPanel();
        Room3B = new javax.swing.JLabel();
        sec2Room7Breakin = new javax.swing.JButton();
        sec2Room7Fire = new javax.swing.JButton();
        Room7Label = new javax.swing.JLabel();
        panelRoom8 = new javax.swing.JPanel();
        sec2Room8Breakin = new javax.swing.JButton();
        sec2Room8Fire = new javax.swing.JButton();
        Room8Label = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        iconImg = new javax.swing.JLabel();
        StartSimulationButton = new javax.swing.JButton();
        

        setTitle("SoSafe Security System");
        setLocation(new java.awt.Point(150, 22));
        getContentPane().setLayout(new java.awt.GridLayout(1, 0));

        bldgPanel.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Building Layout", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Lucida Grande", 0, 18))); // NOI18N
        bldgPanel.setLayout(new java.awt.GridLayout(1, 0));
        
        bldgPanel.setBackground(new Color(152, 175, 199));

        secAPanel.setBorder(javax.swing.BorderFactory.createTitledBorder("Section A"));
        secAPanel.setLayout(new java.awt.GridLayout(2, 2));
        secAPanel.setBackground(new java.awt.Color(153, 153, 153));
        secBPanel.setBackground(new java.awt.Color(153, 153, 153));

        panelRoom1.setBorder(javax.swing.BorderFactory.createTitledBorder("Room 1"));

        sec1Room1Breakin.setText("Breakin");
        sec1Room1Breakin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sec1Room1BreakinActionPerformed(evt);
            }
        });

        sec1Room1Fire.setText("Fire");
        sec1Room1Fire.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sec1Room1FireActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout secARoom1Layout = new javax.swing.GroupLayout(panelRoom1);
        panelRoom1.setLayout(secARoom1Layout);
        secARoom1Layout.setHorizontalGroup(
            secARoom1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(secARoom1Layout.createSequentialGroup()
                .addGap(0, 22, Short.MAX_VALUE)
                .addComponent(sec1Room1Breakin, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(sec1Room1Fire)
                .addGap(27, 27, 27))
            .addGroup(secARoom1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, secARoom1Layout.createSequentialGroup()
                    .addContainerGap(59, Short.MAX_VALUE)
                    .addComponent(Room1Label, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(55, 55, 55)))
        );
        secARoom1Layout.setVerticalGroup(
            secARoom1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(secARoom1Layout.createSequentialGroup()
                .addContainerGap(134, Short.MAX_VALUE)
                .addGroup(secARoom1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(sec1Room1Breakin)
                    .addComponent(sec1Room1Fire))
                .addContainerGap())
            .addGroup(secARoom1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(secARoom1Layout.createSequentialGroup()
                    .addGap(55, 55, 55)
                    .addComponent(Room1Label, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(71, Short.MAX_VALUE)))
        );

        secAPanel.add(panelRoom1);

        panelRoom2.setBorder(javax.swing.BorderFactory.createTitledBorder("Room 2"));

        sec1Room2Breakin.setText("Breakin");
        sec1Room2Breakin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sec1Room2BreakinActionPerformed(evt);
            }
        });

        sec1Room2Fire.setText("Fire");
        sec1Room2Fire.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sec1Room2FireActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout secARoom2Layout = new javax.swing.GroupLayout(panelRoom2);
        panelRoom2.setLayout(secARoom2Layout);
        secARoom2Layout.setHorizontalGroup(
            secARoom2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(secARoom2Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(secARoom2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(secARoom2Layout.createSequentialGroup()
                        .addComponent(sec1Room2Breakin, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(sec1Room2Fire))
                    .addComponent(Room2))
                .addContainerGap(28, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, secARoom2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(Room2Label, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(49, 49, 49))
        );
        secARoom2Layout.setVerticalGroup(
            secARoom2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(secARoom2Layout.createSequentialGroup()
                .addGap(52, 52, 52)
                .addComponent(Room2Label, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Room2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 33, Short.MAX_VALUE)
                .addGroup(secARoom2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(sec1Room2Breakin)
                    .addComponent(sec1Room2Fire))
                .addContainerGap())
        );

        secAPanel.add(panelRoom2);

        panelRoom3.setBorder(javax.swing.BorderFactory.createTitledBorder("Room 3"));

        sec1Room3Fire.setText("Fire");
        sec1Room3Fire.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sec1Room3FireActionPerformed(evt);
            }
        });

        sec1Room3Breakin.setText("Breakin");
        sec1Room3Breakin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sec1Room3BreakinActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout secARoom3Layout = new javax.swing.GroupLayout(panelRoom3);
        panelRoom3.setLayout(secARoom3Layout);
        secARoom3Layout.setHorizontalGroup(
            secARoom3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(secARoom3Layout.createSequentialGroup()
                .addGroup(secARoom3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(secARoom3Layout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addComponent(Room3))
                    .addGroup(secARoom3Layout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addComponent(sec1Room3Breakin, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(sec1Room3Fire)))
                .addContainerGap(26, Short.MAX_VALUE))
            .addGroup(secARoom3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, secARoom3Layout.createSequentialGroup()
                    .addContainerGap(60, Short.MAX_VALUE)
                    .addComponent(Room3Label, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(54, 54, 54)))
        );
        secARoom3Layout.setVerticalGroup(
            secARoom3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(secARoom3Layout.createSequentialGroup()
                .addGap(58, 58, 58)
                .addComponent(Room3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 68, Short.MAX_VALUE)
                .addGroup(secARoom3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(sec1Room3Breakin)
                    .addComponent(sec1Room3Fire))
                .addGap(14, 14, 14))
            .addGroup(secARoom3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(secARoom3Layout.createSequentialGroup()
                    .addGap(57, 57, 57)
                    .addComponent(Room3Label, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(69, Short.MAX_VALUE)))
        );

        secAPanel.add(panelRoom3);

        panelRoom4.setBorder(javax.swing.BorderFactory.createTitledBorder("Room 4"));

        sec1Room4Breakin.setText("Breakin");
        sec1Room4Breakin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sec1Room4BreakinActionPerformed(evt);
            }
        });

        sec1Room4Fire.setText("Fire");
        sec1Room4Fire.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sec1Room4FireActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout secARoom4Layout = new javax.swing.GroupLayout(panelRoom4);
        panelRoom4.setLayout(secARoom4Layout);
        secARoom4Layout.setHorizontalGroup(
            secARoom4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(secARoom4Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(secARoom4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(secARoom4Layout.createSequentialGroup()
                        .addComponent(sec1Room4Breakin, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(sec1Room4Fire))
                    .addGroup(secARoom4Layout.createSequentialGroup()
                        .addComponent(Room4)
                        .addGap(32, 32, 32)
                        .addComponent(Room4Label, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(26, Short.MAX_VALUE))
        );
        secARoom4Layout.setVerticalGroup(
            secARoom4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(secARoom4Layout.createSequentialGroup()
                .addGroup(secARoom4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(secARoom4Layout.createSequentialGroup()
                        .addGap(66, 66, 66)
                        .addComponent(Room4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, secARoom4Layout.createSequentialGroup()
                        .addContainerGap(53, Short.MAX_VALUE)
                        .addComponent(Room4Label, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(29, 29, 29)))
                .addGroup(secARoom4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(sec1Room4Breakin)
                    .addComponent(sec1Room4Fire))
                .addGap(15, 15, 15))
        );

        secAPanel.add(panelRoom4);

        bldgPanel.add(secAPanel);

        secBPanel.setBorder(javax.swing.BorderFactory.createTitledBorder("Section B"));
        secBPanel.setLayout(new java.awt.GridLayout(2, 2));

        panelRoom5.setBorder(javax.swing.BorderFactory.createTitledBorder("Room 5"));

        sec2Room5Breakin.setText("Breakin");
        sec2Room5Breakin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sec2Room5BreakinActionPerformed(evt);
            }
        });

        sec2Room5Fire.setText("Fire");
        sec2Room5Fire.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sec2Room5FireActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout secBRoom1Layout = new javax.swing.GroupLayout(panelRoom5);
        panelRoom5.setLayout(secBRoom1Layout);
        secBRoom1Layout.setHorizontalGroup(
            secBRoom1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(secBRoom1Layout.createSequentialGroup()
                .addGroup(secBRoom1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(secBRoom1Layout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addComponent(Room1B))
                    .addGroup(secBRoom1Layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(sec2Room5Breakin, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(sec2Room5Fire)))
                .addContainerGap(23, Short.MAX_VALUE))
            .addGroup(secBRoom1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(secBRoom1Layout.createSequentialGroup()
                    .addGap(56, 56, 56)
                    .addComponent(Room5Label, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(58, Short.MAX_VALUE)))
        );
        secBRoom1Layout.setVerticalGroup(
            secBRoom1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(secBRoom1Layout.createSequentialGroup()
                .addGap(76, 76, 76)
                .addComponent(Room1B)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 58, Short.MAX_VALUE)
                .addGroup(secBRoom1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(sec2Room5Breakin)
                    .addComponent(sec2Room5Fire))
                .addContainerGap())
            .addGroup(secBRoom1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(secBRoom1Layout.createSequentialGroup()
                    .addGap(57, 57, 57)
                    .addComponent(Room5Label, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(69, Short.MAX_VALUE)))
        );

        secBPanel.add(panelRoom5);

        panelRoom6.setBorder(javax.swing.BorderFactory.createTitledBorder("Room 6"));

        sec2Room6Breakin.setText("Breakin");
        sec2Room6Breakin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sec2Room6BreakinActionPerformed(evt);
            }
        });

        sec2Room6Fire.setText("Fire");
        sec2Room6Fire.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sec2Room6FireActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout secBRoom2Layout = new javax.swing.GroupLayout(panelRoom6);
        panelRoom6.setLayout(secBRoom2Layout);
        secBRoom2Layout.setHorizontalGroup(
            secBRoom2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(secBRoom2Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(sec2Room6Breakin, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(sec2Room6Fire)
                .addContainerGap(24, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, secBRoom2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(Room6Label, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(44, 44, 44))
        );
        secBRoom2Layout.setVerticalGroup(
            secBRoom2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, secBRoom2Layout.createSequentialGroup()
                .addContainerGap(54, Short.MAX_VALUE)
                .addComponent(Room6Label, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(37, 37, 37)
                .addGroup(secBRoom2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(sec2Room6Breakin)
                    .addComponent(sec2Room6Fire))
                .addContainerGap())
        );

        secBPanel.add(panelRoom6);

        panelRoom7.setBorder(javax.swing.BorderFactory.createTitledBorder("Room 7"));

        sec2Room7Breakin.setText("Breakin");
        sec2Room7Breakin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sec2Room7BreakinActionPerformed(evt);
            }
        });

        sec2Room7Fire.setText("Fire");
        sec2Room7Fire.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sec2Room7FireActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout secBRoom3Layout = new javax.swing.GroupLayout(panelRoom7);
        panelRoom7.setLayout(secBRoom3Layout);
        secBRoom3Layout.setHorizontalGroup(
            secBRoom3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(secBRoom3Layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addGroup(secBRoom3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(secBRoom3Layout.createSequentialGroup()
                        .addComponent(sec2Room7Breakin, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(sec2Room7Fire))
                    .addGroup(secBRoom3Layout.createSequentialGroup()
                        .addComponent(Room3B)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(Room7Label, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(12, Short.MAX_VALUE))
        );
        secBRoom3Layout.setVerticalGroup(
            secBRoom3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(secBRoom3Layout.createSequentialGroup()
                .addGroup(secBRoom3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(secBRoom3Layout.createSequentialGroup()
                        .addGap(61, 61, 61)
                        .addComponent(Room3B)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, secBRoom3Layout.createSequentialGroup()
                        .addContainerGap(49, Short.MAX_VALUE)
                        .addComponent(Room7Label, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(33, 33, 33)))
                .addGroup(secBRoom3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(sec2Room7Breakin)
                    .addComponent(sec2Room7Fire))
                .addGap(15, 15, 15))
        );

        secBPanel.add(panelRoom7);

        panelRoom8.setBorder(javax.swing.BorderFactory.createTitledBorder("Room 8"));

        sec2Room8Breakin.setText("Breakin");
        sec2Room8Breakin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sec2Room8BreakinActionPerformed(evt);
            }
        });

        sec2Room8Fire.setText("Fire");
        sec2Room8Fire.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sec2Room8FireActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout secBRoom4Layout = new javax.swing.GroupLayout(panelRoom8);
        panelRoom8.setLayout(secBRoom4Layout);
        secBRoom4Layout.setHorizontalGroup(
            secBRoom4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(secBRoom4Layout.createSequentialGroup()
                .addGroup(secBRoom4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(secBRoom4Layout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addComponent(sec2Room8Breakin, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(sec2Room8Fire))
                    .addGroup(secBRoom4Layout.createSequentialGroup()
                        .addGap(52, 52, 52)
                        .addComponent(Room8Label, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(13, Short.MAX_VALUE))
        );
        secBRoom4Layout.setVerticalGroup(
            secBRoom4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(secBRoom4Layout.createSequentialGroup()
                .addContainerGap(50, Short.MAX_VALUE)
                .addComponent(Room8Label, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(33, 33, 33)
                .addGroup(secBRoom4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(sec2Room8Fire)
                    .addComponent(sec2Room8Breakin))
                .addGap(14, 14, 14))
        );

        secBPanel.add(panelRoom8);

        bldgPanel.add(secBPanel);

        jLabel1.setFont(new java.awt.Font("PT Sans Caption", 1, 24)); // NOI18N
        jLabel1.setText("SoSafe Security System");

        iconImg.setIcon(new javax.swing.ImageIcon("home.png")); // NOI18N
        iconImg.setText("jLabel2");

        StartSimulationButton.setText("Start Simulation");
        StartSimulationButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                StartSimulationButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout topPanelLayout = new javax.swing.GroupLayout(topPanel);
        topPanel.setLayout(topPanelLayout);
        topPanelLayout.setHorizontalGroup(
            topPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(topPanelLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(topPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(topPanelLayout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(168, 168, 168)
                        .addComponent(iconImg, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(bldgPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 891, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(29, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, topPanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(StartSimulationButton)
                .addGap(394, 394, 394))
        );
        topPanelLayout.setVerticalGroup(
            topPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(topPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(topPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(iconImg, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(bldgPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 441, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(StartSimulationButton)
                .addContainerGap(22, Short.MAX_VALUE))
        );

        getContentPane().add(topPanel);

        pack();
    }// </editor-fold>                        

    private void sec1Room1BreakinActionPerformed(java.awt.event.ActionEvent evt) {                                                 
    	boolean flag = false;
    	if(panelRoom1.getBackground().equals(Color.GREEN)){
    		flag = true;
    	}
    	
        if(flag){
	    	ringer.ringAlarm("Alarm");
	    	SysLogger.getInstance().writeToLogFile(Calendar.getInstance().getTime(), SysConstants.SECURITY_SERVICE, SysConstants.ROOM_1);
	    	showDialog();
        }

    }                                                

    private void sec1Room2BreakinActionPerformed(java.awt.event.ActionEvent evt) {                                                 
    	boolean flag = false;
    	if(panelRoom2.getBackground().equals(Color.GREEN)){
    		flag = true;
    	}
    	
        if(flag){
        	ringer.ringAlarm("Alarm");
        	SysLogger.getInstance().writeToLogFile(Calendar.getInstance().getTime(), SysConstants.SECURITY_SERVICE, SysConstants.ROOM_2);
	    	showDialog();
        }
    }
                                                    

    private void sec2Room5BreakinActionPerformed(java.awt.event.ActionEvent evt) {                                                 
    	boolean flag = false;
    	if(panelRoom5.getBackground().equals(Color.GREEN)){
    		flag = true;
    	}
    	
        if(flag){
        	ringer.ringAlarm("Alarm");
	    	SysLogger.getInstance().writeToLogFile(Calendar.getInstance().getTime(), SysConstants.SECURITY_SERVICE, SysConstants.ROOM_5);
	    	showDialog();
        }
    }
                                                   

    private void sec2Room6BreakinActionPerformed(java.awt.event.ActionEvent evt) {                                                 
    	boolean flag = false;
    	if(panelRoom6.getBackground().equals(Color.GREEN)){
    		flag = true;
    	}
    	
        if(flag){
        	ringer.ringAlarm("Alarm");
	    	SysLogger.getInstance().writeToLogFile(Calendar.getInstance().getTime(), SysConstants.SECURITY_SERVICE, SysConstants.ROOM_6);
	    	showDialog();
        }
   	}
                                                    

    private void sec1Room3BreakinActionPerformed(java.awt.event.ActionEvent evt) {                                                 
    	boolean flag = false;
    	if(panelRoom3.getBackground().equals(Color.GREEN)){
    		flag = true;
    	}
    	
        if(flag){
        	ringer.ringAlarm("Alarm");
	    	SysLogger.getInstance().writeToLogFile(Calendar.getInstance().getTime(), SysConstants.SECURITY_SERVICE, SysConstants.ROOM_3);
	    	showDialog();
        }
    }
                                                    

    private void sec1Room4BreakinActionPerformed(java.awt.event.ActionEvent evt) {                                                 
    	boolean flag = false;
    	if(panelRoom4.getBackground().equals(Color.GREEN)){
    		flag = true;
    	}
    	
        if(flag){
        	ringer.ringAlarm("Alarm");
	    	SysLogger.getInstance().writeToLogFile(Calendar.getInstance().getTime(), SysConstants.SECURITY_SERVICE, SysConstants.ROOM_4);
	    	showDialog();
         }
    }
                                                    

    private void sec2Room7BreakinActionPerformed(java.awt.event.ActionEvent evt) {                                                 
    	boolean flag = false;
    	if(panelRoom7.getBackground().equals(Color.GREEN)){
    		flag = true;
    	}
    	
        if(flag){
        	ringer.ringAlarm("Alarm");
	    	SysLogger.getInstance().writeToLogFile(Calendar.getInstance().getTime(), SysConstants.SECURITY_SERVICE, SysConstants.ROOM_7);
	    	showDialog();
         }
        }                              

    private void sec1Room1FireActionPerformed(java.awt.event.ActionEvent evt) {                                              
    	boolean flag = true;
    	if(Room1Label.getIcon()== null){
    		flag = false;
    	}
	
        if(flag){
        	ringer.ringAlarm("Alarm");
	    	SysLogger.getInstance().writeToLogFile(Calendar.getInstance().getTime(), SysConstants.FIRE_SERVIC, SysConstants.ROOM_1);
	    	showDialog();
         }}                                     

    private void sec1Room2FireActionPerformed(java.awt.event.ActionEvent evt) {                                              
    	boolean flag = true;
    	if(Room2Label.getIcon()== null){
    		flag = false;
    	}
    	
        if(flag){
        	ringer.ringAlarm("Alarm");
	    	SysLogger.getInstance().writeToLogFile(Calendar.getInstance().getTime(), SysConstants.FIRE_SERVIC, SysConstants.ROOM_2);
	    	showDialog();
         }}
    
    private void sec2Room5FireActionPerformed(java.awt.event.ActionEvent evt) {                                              
    	boolean flag = true;
    	if(Room5Label.getIcon()== null){
    		flag = false;
    	}
    	
        if(flag){
        	ringer.ringAlarm("Alarm");
	    	SysLogger.getInstance().writeToLogFile(Calendar.getInstance().getTime(), SysConstants.FIRE_SERVIC, SysConstants.ROOM_5);
	    	showDialog();
         }}                               

    private void sec2Room6FireActionPerformed(java.awt.event.ActionEvent evt) {                                              
    	boolean flag = true;
    	if(Room6Label.getIcon()== null){
    		flag = false;
    	}
    	
        if(flag){
        	ringer.ringAlarm("Alarm");
	    	SysLogger.getInstance().writeToLogFile(Calendar.getInstance().getTime(), SysConstants.FIRE_SERVIC, SysConstants.ROOM_6);
	    	showDialog();
         }}                                

    private void sec1Room3FireActionPerformed(java.awt.event.ActionEvent evt) {                                              
    	boolean flag = true;
    	if(Room3Label.getIcon()== null){
    		flag = false;
    	}
    	
        if(flag){
        	ringer.ringAlarm("Alarm");
	    	SysLogger.getInstance().writeToLogFile(Calendar.getInstance().getTime(), SysConstants.FIRE_SERVIC, SysConstants.ROOM_3);
	    	showDialog();
         }}
    
    private void sec1Room4FireActionPerformed(java.awt.event.ActionEvent evt) {                                              
    	boolean flag = true;
    	if(Room4Label.getIcon()== null){
    		flag = false;
    	}
    	
        if(flag){
        	ringer.ringAlarm("Alarm");
	    	SysLogger.getInstance().writeToLogFile(Calendar.getInstance().getTime(), SysConstants.FIRE_SERVIC, SysConstants.ROOM_4);
	    	showDialog();
         }}                                

    private void sec2Room7FireActionPerformed(java.awt.event.ActionEvent evt) {                                              
    	boolean flag = true;
    	if(Room7Label.getIcon()== null){
    		flag = false;
    	}
    	
        if(flag){
        	ringer.ringAlarm("Alarm");
	    	SysLogger.getInstance().writeToLogFile(Calendar.getInstance().getTime(), SysConstants.FIRE_SERVIC, SysConstants.ROOM_7);
	    	showDialog();
         }}                                 

    private void sec2Room8FireActionPerformed(java.awt.event.ActionEvent evt) {                                              
    	boolean flag = true;
    	if(Room8Label.getIcon()== null){
    		flag = false;
    	}
    	
        if(flag){
        	ringer.ringAlarm("Alarm");
	    	SysLogger.getInstance().writeToLogFile(Calendar.getInstance().getTime(), SysConstants.FIRE_SERVIC, SysConstants.ROOM_8);
	    	showDialog();
         }}                               

    private void sec2Room8BreakinActionPerformed(java.awt.event.ActionEvent evt) {                                                 
    	boolean flag = false;
    	if(panelRoom8.getBackground().equals(Color.GREEN)){
    		flag = true;
    	}
    	
        if(flag){
        	ringer.ringAlarm("Alarm");
	    	SysLogger.getInstance().writeToLogFile(Calendar.getInstance().getTime(), SysConstants.SECURITY_SERVICE, SysConstants.ROOM_8);
	    	showDialog();
         }
        }                                             

    private void StartSimulationButtonActionPerformed(java.awt.event.ActionEvent evt) {   
    	buildComponentMap();
    	Icon icon = new ImageIcon("fire.png");
    	for(Sensor sensor:sensorList){
    		if(sensor.getClass().isInstance(new MotionSensor())){
    			panelMap.get(sensor.getSensorID()).setBackground(Color.GREEN);
    		}
    		else if(sensor.getClass().isInstance(new TempSensor())){
    			labelMap.get(sensor.getSensorID()).setIcon(icon);
    		}
    	}
    }   
    
    private void buildComponentMap(){
    	panelMap.put(1, panelRoom1);
    	panelMap.put(2, panelRoom2);
    	panelMap.put(3, panelRoom3);
    	panelMap.put(4, panelRoom4);
    	panelMap.put(5, panelRoom5);
    	panelMap.put(6, panelRoom6);
    	panelMap.put(7, panelRoom7);
    	panelMap.put(8, panelRoom8);
    	labelMap.put(1, Room1Label);
    	labelMap.put(2, Room2Label);
    	labelMap.put(3, Room3Label);
    	labelMap.put(4, Room4Label);
    	labelMap.put(5, Room5Label);
    	labelMap.put(6, Room6Label);
    	labelMap.put(7, Room7Label);
    	labelMap.put(8, Room8Label);
    }

    private String showDialog(){
    	SwingUtilities.invokeLater(new Runnable() {
            public void run() {
                responseCode = JOptionPane.showInputDialog("Calling "+sys.getTeleNo()+" ...");
                if(responseCode == null || responseCode.equals("") || !responseCode.equals(sys.getSystemResponseCode())){
                	showDialog();
                	try {
						Thread.sleep(5000);
					} catch (InterruptedException e) {
						e.printStackTrace();
					}
                }
            }
        });
    	return responseCode;
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SimulatorGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SimulatorGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SimulatorGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SimulatorGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SimulatorGUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify                     
    private javax.swing.JLabel Room1B;
    private javax.swing.JLabel Room1Label;
    private javax.swing.JLabel Room2;
    private javax.swing.JLabel Room2Label;
    private javax.swing.JLabel Room3;
    private javax.swing.JLabel Room3B;
    private javax.swing.JLabel Room3Label;
    private javax.swing.JLabel Room4;
    private javax.swing.JLabel Room4Label;
    private javax.swing.JLabel Room5Label;
    private javax.swing.JLabel Room6Label;
    private javax.swing.JLabel Room7Label;
    private javax.swing.JLabel Room8Label;
    private javax.swing.JButton StartSimulationButton;
    private javax.swing.JPanel bldgPanel;
    private javax.swing.JLabel iconImg;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JButton sec1Room1Breakin;
    private javax.swing.JButton sec1Room1Fire;
    private javax.swing.JButton sec1Room2Breakin;
    private javax.swing.JButton sec1Room2Fire;
    private javax.swing.JButton sec1Room3Breakin;
    private javax.swing.JButton sec1Room3Fire;
    private javax.swing.JButton sec1Room4Breakin;
    private javax.swing.JButton sec1Room4Fire;
    private javax.swing.JButton sec2Room5Breakin;
    private javax.swing.JButton sec2Room5Fire;
    private javax.swing.JButton sec2Room6Breakin;
    private javax.swing.JButton sec2Room6Fire;
    private javax.swing.JButton sec2Room7Breakin;
    private javax.swing.JButton sec2Room7Fire;
    private javax.swing.JButton sec2Room8Breakin;
    private javax.swing.JButton sec2Room8Fire;
    private javax.swing.JPanel secAPanel;
    private javax.swing.JPanel panelRoom1;
    private javax.swing.JPanel panelRoom2;
    private javax.swing.JPanel panelRoom3;
    private javax.swing.JPanel panelRoom4;
    private javax.swing.JPanel secBPanel;
    private javax.swing.JPanel panelRoom5;
    private javax.swing.JPanel panelRoom6;
    private javax.swing.JPanel panelRoom7;
    private javax.swing.JPanel panelRoom8;
    private javax.swing.JPanel topPanel;
    private javax.swing.ImageIcon icon;
    private Timer timeline;
    private Player player;

    // End of variables declaration                   
}

                                            
               

