package installCode;
import java.awt.Color;
import java.net.URL;

import javax.media.ControllerEvent;
import javax.media.ControllerListener;
import javax.media.EndOfMediaEvent;
import javax.media.Manager;
import javax.media.MediaLocator;
import javax.media.Player;
import javax.swing.ImageIcon;
import javax.swing.SwingUtilities;
import javax.swing.Timer;
import javax.swing.UIManager;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author saurabh
 */
public class Display extends javax.swing.JFrame {

    /**
     * Creates new form home
     */
    public Display() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        topPanel = new javax.swing.JPanel();
        bldgPanel = new javax.swing.JPanel();
        secAPanel = new javax.swing.JPanel();
        secARoom1 = new javax.swing.JPanel();
        Room1 = new javax.swing.JLabel();
        secARoom2 = new javax.swing.JPanel();
        Room2 = new javax.swing.JLabel();
        secARoom3 = new javax.swing.JPanel();
        Room3 = new javax.swing.JLabel();
        secARoom4 = new javax.swing.JPanel();
        Room4 = new javax.swing.JLabel();
        secBPanel = new javax.swing.JPanel();
        secBRoom1 = new javax.swing.JPanel();
        Room1B = new javax.swing.JLabel();
        secBRoom2 = new javax.swing.JPanel();
        Room2B = new javax.swing.JLabel();
        secBRoom3 = new javax.swing.JPanel();
        Room3B = new javax.swing.JLabel();
        secBRoom4 = new javax.swing.JPanel();
        Room4B = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        selPanel = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        breakInA = new javax.swing.JCheckBox();
        fireA = new javax.swing.JCheckBox();
        jPanel2 = new javax.swing.JPanel();
        breakInB = new javax.swing.JCheckBox();
        fireB = new javax.swing.JCheckBox();
        submit = new java.awt.Button();
        iconImg = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("So Safe Security System - Home");
        setLocation(new java.awt.Point(150, 22));
        getContentPane().setLayout(new java.awt.GridLayout(1, 0));

        bldgPanel.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Building Layout", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Lucida Grande", 0, 18))); // NOI18N
        bldgPanel.setLayout(new java.awt.GridLayout(1, 0));

        secAPanel.setBorder(javax.swing.BorderFactory.createTitledBorder("Section A"));
        secAPanel.setLayout(new java.awt.GridLayout(2, 2));

        secARoom1.setBorder(javax.swing.BorderFactory.createTitledBorder("Room 1"));

        javax.swing.GroupLayout secARoom1Layout = new javax.swing.GroupLayout(secARoom1);
        secARoom1.setLayout(secARoom1Layout);
        secARoom1Layout.setHorizontalGroup(
            secARoom1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, secARoom1Layout.createSequentialGroup()
                .addContainerGap(73, Short.MAX_VALUE)
                .addComponent(Room1, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        secARoom1Layout.setVerticalGroup(
            secARoom1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, secARoom1Layout.createSequentialGroup()
                .addContainerGap(77, Short.MAX_VALUE)
                .addComponent(Room1, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        secAPanel.add(secARoom1);

        secARoom2.setBorder(javax.swing.BorderFactory.createTitledBorder("Room 2"));

        javax.swing.GroupLayout secARoom2Layout = new javax.swing.GroupLayout(secARoom2);
        secARoom2.setLayout(secARoom2Layout);
        secARoom2Layout.setHorizontalGroup(
            secARoom2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(secARoom2Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(Room2)
                .addContainerGap(180, Short.MAX_VALUE))
        );
        secARoom2Layout.setVerticalGroup(
            secARoom2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(secARoom2Layout.createSequentialGroup()
                .addGap(52, 52, 52)
                .addComponent(Room2)
                .addContainerGap(117, Short.MAX_VALUE))
        );

        secAPanel.add(secARoom2);

        secARoom3.setBorder(javax.swing.BorderFactory.createTitledBorder("Room 3"));

        javax.swing.GroupLayout secARoom3Layout = new javax.swing.GroupLayout(secARoom3);
        secARoom3.setLayout(secARoom3Layout);
        secARoom3Layout.setHorizontalGroup(
            secARoom3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(secARoom3Layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addComponent(Room3)
                .addContainerGap(169, Short.MAX_VALUE))
        );
        secARoom3Layout.setVerticalGroup(
            secARoom3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(secARoom3Layout.createSequentialGroup()
                .addGap(58, 58, 58)
                .addComponent(Room3)
                .addContainerGap(111, Short.MAX_VALUE))
        );

        secAPanel.add(secARoom3);

        secARoom4.setBorder(javax.swing.BorderFactory.createTitledBorder("Room 4"));

        javax.swing.GroupLayout secARoom4Layout = new javax.swing.GroupLayout(secARoom4);
        secARoom4.setLayout(secARoom4Layout);
        secARoom4Layout.setHorizontalGroup(
            secARoom4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(secARoom4Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(Room4)
                .addContainerGap(178, Short.MAX_VALUE))
        );
        secARoom4Layout.setVerticalGroup(
            secARoom4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(secARoom4Layout.createSequentialGroup()
                .addGap(66, 66, 66)
                .addComponent(Room4)
                .addContainerGap(103, Short.MAX_VALUE))
        );

        secAPanel.add(secARoom4);

        bldgPanel.add(secAPanel);

        secBPanel.setBorder(javax.swing.BorderFactory.createTitledBorder("Section B"));
        secBPanel.setLayout(new java.awt.GridLayout(2, 2));

        secBRoom1.setBorder(javax.swing.BorderFactory.createTitledBorder("Room 1"));

        javax.swing.GroupLayout secBRoom1Layout = new javax.swing.GroupLayout(secBRoom1);
        secBRoom1.setLayout(secBRoom1Layout);
        secBRoom1Layout.setHorizontalGroup(
            secBRoom1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(secBRoom1Layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(Room1B)
                .addContainerGap(173, Short.MAX_VALUE))
        );
        secBRoom1Layout.setVerticalGroup(
            secBRoom1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(secBRoom1Layout.createSequentialGroup()
                .addGap(76, 76, 76)
                .addComponent(Room1B)
                .addContainerGap(93, Short.MAX_VALUE))
        );

        secBPanel.add(secBRoom1);

        secBRoom2.setBorder(javax.swing.BorderFactory.createTitledBorder("Room 2"));

        javax.swing.GroupLayout secBRoom2Layout = new javax.swing.GroupLayout(secBRoom2);
        secBRoom2.setLayout(secBRoom2Layout);
        secBRoom2Layout.setHorizontalGroup(
            secBRoom2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, secBRoom2Layout.createSequentialGroup()
                .addContainerGap(60, Short.MAX_VALUE)
                .addComponent(Room2B, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(14, 14, 14))
        );
        secBRoom2Layout.setVerticalGroup(
            secBRoom2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, secBRoom2Layout.createSequentialGroup()
                .addContainerGap(71, Short.MAX_VALUE)
                .addComponent(Room2B, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(16, 16, 16))
        );

        secBPanel.add(secBRoom2);

        secBRoom3.setBorder(javax.swing.BorderFactory.createTitledBorder("Room 3"));

        javax.swing.GroupLayout secBRoom3Layout = new javax.swing.GroupLayout(secBRoom3);
        secBRoom3.setLayout(secBRoom3Layout);
        secBRoom3Layout.setHorizontalGroup(
            secBRoom3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(secBRoom3Layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addComponent(Room3B)
                .addContainerGap(170, Short.MAX_VALUE))
        );
        secBRoom3Layout.setVerticalGroup(
            secBRoom3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(secBRoom3Layout.createSequentialGroup()
                .addGap(61, 61, 61)
                .addComponent(Room3B)
                .addContainerGap(108, Short.MAX_VALUE))
        );

        secBPanel.add(secBRoom3);

        secBRoom4.setBorder(javax.swing.BorderFactory.createTitledBorder("Room 4"));

        javax.swing.GroupLayout secBRoom4Layout = new javax.swing.GroupLayout(secBRoom4);
        secBRoom4.setLayout(secBRoom4Layout);
        secBRoom4Layout.setHorizontalGroup(
            secBRoom4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, secBRoom4Layout.createSequentialGroup()
                .addContainerGap(65, Short.MAX_VALUE)
                .addComponent(Room4B, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(14, 14, 14))
        );
        secBRoom4Layout.setVerticalGroup(
            secBRoom4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, secBRoom4Layout.createSequentialGroup()
                .addContainerGap(76, Short.MAX_VALUE)
                .addComponent(Room4B, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(14, 14, 14))
        );

        secBPanel.add(secBRoom4);

        bldgPanel.add(secBPanel);

        jLabel1.setFont(new java.awt.Font("PT Sans Caption", 3, 24)); // NOI18N
        jLabel1.setText("So Safe Security System");

        selPanel.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Select Alarms", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Lucida Grande", 0, 14))); // NOI18N
        selPanel.setLayout(new java.awt.GridLayout(1, 0));

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Section A"));

        breakInA.setText("Break-in");
        breakInA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                breakInAActionPerformed(evt);
            }
        });

        fireA.setText("Fire");
        fireA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fireAActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(fireA)
                    .addComponent(breakInA))
                .addContainerGap(319, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(breakInA)
                .addGap(18, 18, 18)
                .addComponent(fireA)
                .addContainerGap(38, Short.MAX_VALUE))
        );

        selPanel.add(jPanel1);

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Section B"));

        breakInB.setText("Break-in");
        breakInB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                breakInBActionPerformed(evt);
            }
        });

        fireB.setText("Fire");
        fireB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fireBActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(fireB)
                    .addComponent(breakInB))
                .addContainerGap(321, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(breakInB)
                .addGap(18, 18, 18)
                .addComponent(fireB)
                .addContainerGap(38, Short.MAX_VALUE))
        );

        selPanel.add(jPanel2);

        submit.setLabel("Simulate");
        submit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submitActionPerformed(evt);
            }
        });

        iconImg.setIcon(new javax.swing.ImageIcon("/Users/saurabh/Desktop/home.png")); // NOI18N
        iconImg.setText("jLabel2");

        javax.swing.GroupLayout topPanelLayout = new javax.swing.GroupLayout(topPanel);
        topPanel.setLayout(topPanelLayout);
        topPanelLayout.setHorizontalGroup(
            topPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(topPanelLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(topPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(submit, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(topPanelLayout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(189, 189, 189)
                        .addComponent(iconImg, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(topPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(bldgPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 891, Short.MAX_VALUE)
                        .addComponent(selPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGap(25, 25, 25))
        );
        topPanelLayout.setVerticalGroup(
            topPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(topPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(topPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(iconImg, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(bldgPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 441, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(selPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(1, 1, 1)
                .addComponent(submit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(40, Short.MAX_VALUE))
        );

        getContentPane().add(topPanel);

        pack();
    }// </editor-fold>                        

    private void submitActionPerformed(java.awt.event.ActionEvent evt) {    
    	if(breakInA.isSelected() || breakInB.isSelected() || fireA.isSelected() || fireB.isSelected()) {
    	try {
    		
            URL url = this.getClass().getClassLoader().getResource("Alarm.wav");
            System.out.println("Alarm file:"+url);
            MediaLocator locator = new MediaLocator(url);
            player = Manager.createPlayer(locator);
            player.addControllerListener(new ControllerListener() {
               public void controllerUpdate(ControllerEvent event) {
                  if (event instanceof EndOfMediaEvent) {
                     player.stop();
                     player.close();
                  }
               }
            });
            player.realize();
            player.start();
         } catch (Exception e) {
            e.printStackTrace();
         }
    	}
    }                                      

    private void breakInAActionPerformed(java.awt.event.ActionEvent evt) {                                         
        if(breakInA.isSelected())
        {
        secARoom1.setBackground(Color.RED);
        /**final Timeline timeline = new Timeline(secARoom1);
        timeline.addPropertyToInterpolate("background", secARoom1.getBackground(),
                Color.red);
        timeline.setDuration(1000);

        timeline.playLoop(5, RepeatBehavior.REVERSE);**/
        
        secARoom2.setBackground(Color.RED);
        secARoom3.setBackground(Color.RED);
        secARoom4.setBackground(Color.RED);
        }
        else{
        	secARoom1.setBackground(UIManager.getColor ( "Panel.background" ));
            secARoom2.setBackground(UIManager.getColor ( "Panel.background" ));
            secARoom3.setBackground(UIManager.getColor ( "Panel.background" ));
            secARoom4.setBackground(UIManager.getColor ( "Panel.background" ));
        }
        
       
        
                // TODO add your handling code here:
    }  

    private void fireAActionPerformed(java.awt.event.ActionEvent evt) {                                      
        // TODO add your handling code here:
    	icon = new ImageIcon ("fire.png");
	    if(fireA.isSelected()){
	    	Room1.setIcon(icon);
	    	Room2.setIcon(icon);
	    	Room3.setIcon(icon);
	    	Room4.setIcon(icon);
	    	
	    	Room1.setVisible(true);
	    	Room2.setVisible(true);
	    	Room3.setVisible(true);
	    	Room4.setVisible(true);
	    }
	    	
	    else {
	    	Room1.setVisible(false);
	    	Room2.setVisible(false);
	    	Room3.setVisible(false);
	    	Room4.setVisible(false);
	    }
 } 
     private void breakInBActionPerformed(java.awt.event.ActionEvent evt) {                                              
        if(breakInB.isSelected())
        {
        secBRoom1.setBackground(Color.RED);
        secBRoom2.setBackground(Color.RED);
        secBRoom3.setBackground(Color.RED);
        secBRoom4.setBackground(Color.RED);
        }
        else{
        	secBRoom1.setBackground(UIManager.getColor ( "Panel.background" ));
            secBRoom2.setBackground(UIManager.getColor ( "Panel.background" ));
            secBRoom3.setBackground(UIManager.getColor ( "Panel.background" ));
            secBRoom4.setBackground(UIManager.getColor ( "Panel.background" ));
        }
        
       
        
                // TODO add your handling code here:
    }                                             

    private void fireBActionPerformed(java.awt.event.ActionEvent evt) {                                      
    	icon = new ImageIcon ("fire.png");
	    if(fireB.isSelected()){
	    	Room1B.setIcon(icon);
	    	Room2B.setIcon(icon);
	    	Room3B.setIcon(icon);
	    	Room4B.setIcon(icon);
	    	
	    	Room1B.setVisible(true);
	    	Room2B.setVisible(true);
	    	Room3B.setVisible(true);
	    	Room4B.setVisible(true);
	    }
	    	
	    else {
	    	Room1B.setVisible(false);
	    	Room2B.setVisible(false);
	    	Room3B.setVisible(false);
	    	Room4B.setVisible(false);
	    }
 }                                   

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
    	/*SwingUtilities.invokeLater(new Runnable() {
    		 SwingUtilities.invokeLater(new Runnable() {
    	            public void run() {
    	                createAndShowGUI();
    	            }
    	        });*/
    	try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Display.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Display.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Display.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Display.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Display().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify                     
    private javax.swing.JLabel Room1;
    private javax.swing.JLabel Room1B;
    private javax.swing.JLabel Room2;
    private javax.swing.JLabel Room2B;
    private javax.swing.JLabel Room3;
    private javax.swing.JLabel Room3B;
    private javax.swing.JLabel Room4;
    private javax.swing.JLabel Room4B;
    private javax.swing.JPanel bldgPanel;
    private javax.swing.JCheckBox breakInA;
    private javax.swing.JCheckBox breakInB;
    private javax.swing.JCheckBox fireA;
    private javax.swing.JCheckBox fireB;
    private javax.swing.JLabel iconImg;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel secAPanel;
    private javax.swing.JPanel secARoom1;
    private javax.swing.JPanel secARoom2;
    private javax.swing.JPanel secARoom3;
    private javax.swing.JPanel secARoom4;
    private javax.swing.JPanel secBPanel;
    private javax.swing.JPanel secBRoom1;
    private javax.swing.JPanel secBRoom2;
    private javax.swing.JPanel secBRoom3;
    private javax.swing.JPanel secBRoom4;
    private javax.swing.JPanel selPanel;
    private java.awt.Button submit;
    private javax.swing.JPanel topPanel;
    private javax.swing.ImageIcon icon;
    private Timer timeline;
    private Player player;
    // End of variables declaration                   
}
